from enum import Enum

class ComplaintStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_INFO = "PENDING_INFO"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class TicketStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_INFO = "PENDING_INFO"
    CLOSED = "CLOSED"

class EscalationReason(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    USER_REQUEST = "USER_REQUEST"
    HIGH_AMOUNT = "HIGH_AMOUNT"
    WORKFLOW_FAILURE = "WORKFLOW_FAILURE"

class WalletStatus(str, Enum):
    PENDING = "PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class DialogState(str, Enum):
    GREETING = "GREETING"
    INTENT_DETECTION = "INTENT_DETECTION"
    FAQ_RESPONSE = "FAQ_RESPONSE"
    COMPLAINT_COLLECTION = "COMPLAINT_COLLECTION"
    COMPLAINT_CONFIRMATION = "COMPLAINT_CONFIRMATION"
    WALLET_VALIDATION = "WALLET_VALIDATION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    CLOSED = "CLOSED"

class Priority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"
